name: TensorFlow Serving CI/CD

on: [push]

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image for TensorFlow Serving
      run: docker build . --file Dockerfile.serving --tag mohammad3500/diabetes-prediction-serving

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push the Docker image for TensorFlow Serving
      run: docker push mohammad3500/diabetes-prediction-serving
